service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-cli
  region: us-east-2
  stage: dev

plugins:
  - serverless-offline

functions:
  collect:
    handler: src/collect/collect.handler
    events:
      - http: ANY /
      - http: 'ANY /{param+}'

  api:
    handler: src/api/api.handler
    events:
      - http: GET /api

  todos:
    handler: src/api/todos.handler
    events:
      - http:
          path: /todo
          method: GET

  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: /todo/{id}
          method: GET
          request:
            parameters:
              id: true

  hello:
    handler: handler.hello

  helloworld:
    handler: src/helloworld.handler

  fnevent:
    handler: src/fnevent.handler
